2016-11-04 16:08:15,128 - arteria.web.app - INFO - Logger initialized by AppService
2016-11-04 16:08:15,137 - arteria.configuration - INFO - Read config file from /home/dahljo/workspace/arteria/arteria-delivery/tests/integration_tests/../../config/app.config, format=<built-in function format>, from_cache=True
2016-11-04 16:08:15,152 - arteria.configuration - INFO - Read config file from /home/dahljo/workspace/arteria/arteria-delivery/tests/integration_tests/../../config/logger.config, format=<built-in function format>, from_cache=True
2016-11-04 16:08:15,153 - arteria.web.app - INFO - Logger initialized by AppService
2016-11-04 16:08:15,158 - delivery.repositories.runfolder_repository - DEBUG - Listing dirs in: /home/dahljo/workspace/arteria/arteria-delivery/tests/tests/resources
2016-11-04 16:08:15,158 - tornado.application - ERROR - Uncaught exception GET /api/1.0/runfolders (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:53820', method='GET', uri='/api/1.0/runfolders', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'close', 'Host': 'localhost:53820', 'Accept-Encoding': 'gzip'})
Traceback (most recent call last):
  File "/home/dahljo/anaconda/envs/arteria-delivery/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/handlers/runfolder_handlers.py", line 24, in get
    runfolders = list(self.runfolder_repo.get_runfolders())
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/runfolder_repository.py", line 44, in _get_runfolders
    for directory in directories:
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/runfolder_repository.py", line 18, in _list_directories
    for my_dir in os.listdir(base_path):
OSError: [Errno 2] No such file or directory: 'tests/resources/'
2016-11-04 16:08:15,159 - tornado.access - ERROR - 500 GET /api/1.0/runfolders (127.0.0.1) 2.00ms
2016-11-04 16:08:15,165 - arteria.configuration - INFO - Read config file from /home/dahljo/workspace/arteria/arteria-delivery/tests/integration_tests/../../config/app.config, format=<built-in function format>, from_cache=True
2016-11-04 16:08:15,173 - arteria.configuration - INFO - Read config file from /home/dahljo/workspace/arteria/arteria-delivery/tests/integration_tests/../../config/logger.config, format=<built-in function format>, from_cache=True
2016-11-04 16:08:15,174 - arteria.web.app - INFO - Logger initialized by AppService
2016-11-04 16:08:15,177 - delivery.repositories.runfolder_repository - DEBUG - Listing dirs in: /home/dahljo/workspace/arteria/arteria-delivery/tests/tests/resources
2016-11-04 16:08:15,178 - tornado.application - ERROR - Uncaught exception GET /api/1.0/projects (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:46475', method='GET', uri='/api/1.0/projects', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'close', 'Host': 'localhost:46475', 'Accept-Encoding': 'gzip'})
Traceback (most recent call last):
  File "/home/dahljo/anaconda/envs/arteria-delivery/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/handlers/project_handlers.py", line 24, in get
    projects = list(self.project_repo.get_projects())
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/project_repository.py", line 9, in get_projects
    for runfolder in self.runfolder_repository.get_runfolders():
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/runfolder_repository.py", line 44, in _get_runfolders
    for directory in directories:
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/runfolder_repository.py", line 18, in _list_directories
    for my_dir in os.listdir(base_path):
OSError: [Errno 2] No such file or directory: 'tests/resources/'
2016-11-04 16:08:15,179 - tornado.access - ERROR - 500 GET /api/1.0/projects (127.0.0.1) 1.64ms
2016-11-04 16:08:15,184 - arteria.configuration - INFO - Read config file from /home/dahljo/workspace/arteria/arteria-delivery/tests/integration_tests/../../config/app.config, format=<built-in function format>, from_cache=True
2016-11-04 16:08:15,192 - arteria.configuration - INFO - Read config file from /home/dahljo/workspace/arteria/arteria-delivery/tests/integration_tests/../../config/logger.config, format=<built-in function format>, from_cache=True
2016-11-04 16:08:15,193 - arteria.web.app - INFO - Logger initialized by AppService
2016-11-04 16:08:15,215 - delivery.handlers.staging_handlers - DEBUG - Trying to stage runfolder with id: 160930_ST-E00216_0111_BH37CWALXX
2016-11-04 16:08:15,215 - delivery.repositories.runfolder_repository - DEBUG - Listing dirs in: /home/dahljo/workspace/arteria/arteria-delivery/tests/tests/resources
2016-11-04 16:08:15,215 - tornado.application - ERROR - Uncaught exception POST /api/1.0/stage/runfolder/160930_ST-E00216_0111_BH37CWALXX (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:40675', method='POST', uri='/api/1.0/stage/runfolder/160930_ST-E00216_0111_BH37CWALXX', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '0', 'Connection': 'close', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'localhost:40675', 'Accept-Encoding': 'gzip'})
Traceback (most recent call last):
  File "/home/dahljo/anaconda/envs/arteria-delivery/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/handlers/staging_handlers.py", line 36, in post
    staging_order_ids = self.staging_service.stage_runfolder(runfolder_id, projects_to_stage)
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/services/staging_service.py", line 104, in stage_runfolder
    runfolder = self.runfolder_repo.get_runfolder(runfolder_id)
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/runfolder_repository.py", line 72, in get_runfolder
    matching_name = [r for r in runfolders if r.name == runfolder]
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/runfolder_repository.py", line 44, in _get_runfolders
    for directory in directories:
  File "/home/dahljo/workspace/arteria/arteria-delivery/delivery/repositories/runfolder_repository.py", line 18, in _list_directories
    for my_dir in os.listdir(base_path):
OSError: [Errno 2] No such file or directory: 'tests/resources/'
2016-11-04 16:08:15,216 - tornado.access - ERROR - 500 POST /api/1.0/stage/runfolder/160930_ST-E00216_0111_BH37CWALXX (127.0.0.1) 2.21ms
